version: '3.8'

services:
  agendabot:
    build: .
    container_name: agendabot-ts
    ports:
      - "3001:3001"
    volumes:
      - ./auth_info_baileys:/app/auth_info_baileys
      - ./credentials:/app/credentials
      - ./calendar_id.txt:/app/calendar_id.txt
      - ./notification.json:/app/notification.json
      - ./system.log:/app/system.log
    restart: always
    environment:
      - PORT=3001
      - NODE_ENV=production
